name: Go

on:
  push:
    branches:
      - main
      - debug
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v ./...

    - name: Unit tests
      run: go test -v -p=1 ./...

    - name: Integration tests
      run: docker-compose -f build/compose/docker-compose-cluster.yml up -V --remove-orphans --build --abort-on-container-exit --exit-code-from client_test

